<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="NUnit.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Avalonia.Headless.NUnit" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OutWit.Common.MVVM.Navigation.Avalonia\OutWit.Common.MVVM.Navigation.Avalonia.csproj" />
		<ProjectReference Include="..\OutWit.Common.MVVM.Navigation\OutWit.Common.MVVM.Navigation.csproj" />
		<ProjectReference Include="..\OutWit.Common.MVVM\OutWit.Common.MVVM.csproj" />
		<ProjectReference Include="..\..\NUnit\OutWit.Common.NUnit\OutWit.Common.NUnit.csproj" />
	</ItemGroup>

</Project>
