<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MVVM\OutWit.Common.MVVM\OutWit.Common.MVVM.csproj" />
  </ItemGroup>

</Project>
