using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OutWit.Common.DependencyInjection.Generator
{
    /// <summary>
    /// Emits the boilerplate <see cref="System.IServiceProvider"/> constructor and
    /// matching <c>Services</c> property for every <c>partial class</c> marked
    /// <c>[InjectableHost]</c>. The emitted <c>Services</c> property is the field
    /// that <c>InjectAspect</c>'s field auto-discovery looks for, so the host
    /// class only needs to declare its <c>[Inject]</c> properties.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class InjectableHostGenerator : IIncrementalGenerator
    {
        #region Constants

        private const string ATTRIBUTE_FULL_NAME = "OutWit.Common.DependencyInjection.InjectableHostAttribute";

        #endregion

        #region Diagnostics

        private static readonly DiagnosticDescriptor MUST_BE_PARTIAL = new(
            id: "OWDI001",
            title: "[InjectableHost] requires a partial class",
            messageFormat: "Class '{0}' is marked [InjectableHost] but is not partial; the generator cannot extend it",
            category: "OutWit.DI",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor MUST_NOT_HAVE_CTOR = new(
            id: "OWDI002",
            title: "[InjectableHost] class declares its own constructor",
            messageFormat: "Class '{0}' is marked [InjectableHost] but already declares a constructor; remove the explicit constructor or drop the attribute",
            category: "OutWit.DI",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        #endregion

        #region IIncrementalGenerator

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ATTRIBUTE_FULL_NAME,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetHostInfo(ctx))
                .Where(static info => info is not null)
                .Select(static (info, _) => info!.Value);

            context.RegisterSourceOutput(candidates, static (spc, info) =>
            {
                if (!info.IsPartial)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(MUST_BE_PARTIAL, info.Location, info.TypeName));
                    return;
                }

                if (info.HasExplicitConstructor)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(MUST_NOT_HAVE_CTOR, info.Location, info.TypeName));
                    return;
                }

                var source = Emit(info);
                spc.AddSource(info.FileName, SourceText.From(source, Encoding.UTF8));
            });
        }

        #endregion

        #region Tools

        private static HostInfo? GetHostInfo(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
                return null;

            var declaration = (ClassDeclarationSyntax)ctx.TargetNode;

            bool isPartial = declaration.Modifiers.Any(m => m.ValueText == "partial");
            bool hasExplicitCtor = typeSymbol.InstanceConstructors
                .Any(c => !c.IsImplicitlyDeclared);

            var ns = typeSymbol.ContainingNamespace?.IsGlobalNamespace == true
                ? null
                : typeSymbol.ContainingNamespace?.ToDisplayString();

            return new HostInfo
            {
                TypeName = typeSymbol.Name,
                Namespace = ns,
                IsPartial = isPartial,
                HasExplicitConstructor = hasExplicitCtor,
                Accessibility = typeSymbol.DeclaredAccessibility,
                FileName = $"{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted))}.InjectableHost.g.cs"
                    .Replace('<', '{').Replace('>', '}'),
                Location = declaration.Identifier.GetLocation()
            };
        }

        private static string Emit(HostInfo info)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();

            var indent = "";
            if (!string.IsNullOrEmpty(info.Namespace))
            {
                sb.Append("namespace ").Append(info.Namespace).AppendLine();
                sb.AppendLine("{");
                indent = "    ";
            }

            sb.Append(indent).Append("partial class ").Append(info.TypeName).AppendLine();
            sb.Append(indent).AppendLine("{");

            sb.Append(indent).AppendLine("    #region InjectableHost (generated)");
            sb.AppendLine();

            var ctorAccess = info.Accessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.ProtectedAndInternal => "private protected",
                _ => "public",
            };

            sb.Append(indent).Append("    ").Append(ctorAccess).Append(' ').Append(info.TypeName).AppendLine("(global::System.IServiceProvider services)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        Services = services;");
            sb.Append(indent).AppendLine("    }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("    private global::System.IServiceProvider Services { get; }");
            sb.AppendLine();
            sb.Append(indent).AppendLine("    #endregion");

            sb.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(info.Namespace))
                sb.AppendLine("}");

            return sb.ToString();
        }

        #endregion

        #region Nested Types

        private struct HostInfo
        {
            public string TypeName { get; set; }
            public string? Namespace { get; set; }
            public bool IsPartial { get; set; }
            public bool HasExplicitConstructor { get; set; }
            public Accessibility Accessibility { get; set; }
            public string FileName { get; set; }
            public Location Location { get; set; }
        }

        #endregion
    }
}
