<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OutWit.Common.MVVM.Navigation.Avalonia\OutWit.Common.MVVM.Navigation.Avalonia.csproj" />
		<ProjectReference Include="..\OutWit.Common.MVVM.Navigation.Sample.Core\OutWit.Common.MVVM.Navigation.Sample.Core.csproj" />
	</ItemGroup>

</Project>
