<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>

		<Version>1.3.2</Version>

		<Description>Logging aspect support for MVVM</Description>
		<PackageTags>OutWit;Common;Aspect;MVVM;Logging</PackageTags>

		<RepositoryUrl>https://github.com/dmitrat/Common/tree/main/Logging/OutWit.Common.Logging</RepositoryUrl>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.TestCorrelator" />
  </ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Serilog.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Serilog.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Serilog.Extensions.Logging" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspects\OutWit.Common.Aspects\OutWit.Common.Aspects.csproj" />
    <ProjectReference Include="..\OutWit.Common.Logging.Abstractions\OutWit.Common.Logging.Abstractions.csproj" />
  </ItemGroup>

</Project>
