<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>

		<Version>1.0.2</Version>

		<Description>Lightweight logging abstractions for the OutWit.Common.Logging ecosystem (ILogManager, ILogger extension helpers).</Description>
		<PackageTags>OutWit;Common;Logging;Abstractions</PackageTags>

		<RepositoryUrl>https://github.com/dmitrat/Common/tree/main/Logging/OutWit.Common.Logging.Abstractions</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

</Project>
