<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OutWit.Common.MVVM.Avalonia\OutWit.Common.MVVM.Avalonia.csproj" />
		<ProjectReference Include="..\OutWit.Common.MVVM.Avalonia.Generator\OutWit.Common.MVVM.Avalonia.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
