using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace OutWit.Common.Licensing.Generator
{
    /// <summary>
    /// Emits a product's licensing vocabulary as constants, from the one file
    /// that defines it.
    /// <para>
    /// It exists for a hazard with no other mitigation: <c>HasFeature("ssoo")</c>
    /// compiles, runs, and quietly disables a capability the customer paid for.
    /// No compiler error, no warning, and not even the unrecognised-key report —
    /// that report sees what the <i>licence</i> granted, never what the
    /// <i>code</i> asked for. A constant turns that into a build failure.
    /// </para>
    /// <para>
    /// It also stops <c>Declares(...)</c> drifting from the keys the product
    /// checks, because both now come from the same file — and that file is the
    /// descriptor the registry can import, which collapses the hand-typed
    /// catalogue hazard to "import what the product already publishes".
    /// </para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class LicenseVocabularyGenerator : IIncrementalGenerator
    {
        #region Constants

        private const string SUFFIX = ".product.json";

        private static readonly DiagnosticDescriptor UNREADABLE = new(
            id: "OWL001",
            title: "The product descriptor could not be read",
            messageFormat: "'{0}' could not be read: {1}",
            category: "OutWit.Licensing",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true,
            description: "A descriptor that failed to parse must stop the build. Falling back to an empty " +
                         "vocabulary would reintroduce the silent failure this generator exists to remove.");

        #endregion

        #region Functions

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var descriptors = context.AdditionalTextsProvider
                .Where(static file => file.Path.EndsWith(SUFFIX, System.StringComparison.OrdinalIgnoreCase))
                .Select(static (file, token) => (file.Path, Text: file.GetText(token)?.ToString() ?? string.Empty));

            var withNamespace = descriptors.Combine(context.AnalyzerConfigOptionsProvider
                .Select(static (options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var value) &&
                    !string.IsNullOrWhiteSpace(value)
                        ? value
                        : "Licensing"));

            context.RegisterSourceOutput(withNamespace, static (production, pair) =>
            {
                var ((path, text), rootNamespace) = pair;

                var descriptor = ProductDescriptor.Read(text, out var error);

                if (descriptor == null)
                {
                    production.ReportDiagnostic(Diagnostic.Create(UNREADABLE, Location.None,
                        System.IO.Path.GetFileName(path), error));

                    return;
                }

                var className = Naming.ClassName(descriptor.Product);

                production.AddSource($"{className}.g.cs",
                    SourceText.From(Render(descriptor, className, rootNamespace), Encoding.UTF8));
            });
        }

        #endregion

        #region Tools

        private static string Render(ProductDescriptor descriptor, string className, string rootNamespace)
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Generated from the product descriptor. Do not edit — edit the *.product.json.");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using OutWit.Common.Licensing;");
            builder.AppendLine("using OutWit.Common.Licensing.Vocabulary;");
            builder.AppendLine();
            builder.AppendLine($"namespace {rootNamespace}");
            builder.AppendLine("{");

            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// Everything the {Naming.Comment(descriptor.Product)} licence can grant, as constants.");
            builder.AppendLine("    /// <para>");
            builder.AppendLine("    /// Generated from the product descriptor, which is also what the licence");
            builder.AppendLine("    /// registry imports — so the keys the code asks about, the keys the runtime");
            builder.AppendLine("    /// is told about and the keys an operator can grant are one list.");
            builder.AppendLine("    /// </para>");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public static class {className}");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>The product key, matched hard against a licence.</summary>");
            builder.AppendLine($"        public const string Product = {Naming.Literal(descriptor.Product)};");
            builder.AppendLine();

            RenderKeys(builder, "Features", "Capabilities this product gates on.", descriptor.Features);
            RenderKeys(builder, "Limits", "Numeric caps this product reads.", descriptor.Limits);

            RenderDeclare(builder, descriptor);

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static void RenderKeys(StringBuilder builder, string groupName, string summary,
            System.Collections.Generic.List<VocabularyEntry> entries)
        {
            builder.AppendLine($"        /// <summary>{summary}</summary>");
            builder.AppendLine($"        public static class {groupName}");
            builder.AppendLine("        {");

            foreach (var entry in entries)
            {
                if (entry.Name.Length > 0)
                    builder.AppendLine($"            /// <summary>{Naming.Comment(entry.Name)}</summary>");

                builder.AppendLine($"            public const string {Naming.Identifier(entry.Key)} = {Naming.Literal(entry.Key)};");
            }

            if (entries.Count == 0)
                builder.AppendLine("            // The descriptor declares none.");

            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private static void RenderDeclare(StringBuilder builder, ProductDescriptor descriptor)
        {
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// Declares this vocabulary to the runtime, so a licence granting");
            builder.AppendLine("        /// something else is reported instead of silently doing nothing.");
            builder.AppendLine("        /// <para>Use as <c>options.Declares(" + Naming.ClassName(descriptor.Product) + ".Declare)</c>.</para>");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        public static void Declare(LicenseVocabulary vocabulary)");
            builder.AppendLine("        {");

            if (descriptor.Features.Count == 0 && descriptor.Limits.Count == 0)
            {
                builder.AppendLine("            // Nothing declared: the product opts out of the unknown-key report.");
            }
            else
            {
                builder.AppendLine("            vocabulary");

                var lines = descriptor.Features
                    .Select(entry => $"                .Feature({Naming.Literal(entry.Key)}, {Naming.Literal(entry.Name)})")
                    .Concat(descriptor.Limits.Select(entry =>
                        $"                .Limit({Naming.Literal(entry.Key)}, {Naming.Literal(entry.Name)}, {Fallback(entry.Default)})"))
                    .ToList();

                for (var index = 0; index < lines.Count; index++)
                    builder.AppendLine(lines[index] + (index == lines.Count - 1 ? ";" : string.Empty));
            }

            builder.AppendLine("        }");
        }

        private static string Fallback(long? value)
        {
            return value == null
                ? "null"
                : value.Value.ToString(CultureInfo.InvariantCulture) + "L";
        }

        #endregion
    }
}
