using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;

namespace OutWit.Common.MVVM.Avalonia.Generator.Generators
{
    internal sealed class StyledPropertyGenerator
    {
        #region Constants

        private const string ARGS_TYPE = "AvaloniaPropertyChangedEventArgs";
        private const string OWNER_TYPE = "AvaloniaObject";
        private const string AVALONIA_OBJECT = "global::Avalonia.AvaloniaObject";

        #endregion

        #region Fields

        private readonly IPropertySymbol m_propertySymbol;
        private readonly INamedTypeSymbol m_containingType;
        private readonly AttributeData m_attributeData;
        private readonly bool m_isAttached;
        private readonly bool m_isDirect;

        #endregion

        #region Constructors

        public StyledPropertyGenerator(
            IPropertySymbol propertySymbol,
            INamedTypeSymbol containingType,
            AttributeData attributeData,
            bool isAttached,
            bool isDirect)
        {
            m_propertySymbol = propertySymbol;
            m_containingType = containingType;
            m_attributeData = attributeData;
            m_isAttached = isAttached;
            m_isDirect = isDirect;
        }

        #endregion

        #region Functions

        public string Generate()
        {
            var namespaceName = m_containingType.ContainingNamespace?.ToDisplayString();
            var className = m_containingType.Name;
            var propertyName = m_propertySymbol.Name;
            var propertyType = m_propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var dpPropertyName = GetAttributeValue<string>("PropertyName") ?? $"{propertyName}Property";
            var defaultValue = GetAttributeValue<object>("DefaultValue");
            var bindsTwoWayByDefault = GetAttributeValue<bool>("BindsTwoWayByDefault");
            var inherits = GetAttributeValue<bool>("Inherits");

            // Convention-based callback discovery
            var onChanged = FindChangedCallback(propertyName);
            var coerce = GetAttributeValue<string>("Coerce") ?? FindCoerceMethod($"{propertyName}Coerce");

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}partial class {className}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    #region Styled Properties");
            sb.AppendLine();

            if (m_isDirect)
            {
                GenerateDirectProperty(sb, indent, dpPropertyName, propertyName, propertyType,
                    defaultValue, bindsTwoWayByDefault, onChanged);
            }
            else if (m_isAttached)
            {
                GenerateAttachedProperty(sb, indent, dpPropertyName, propertyName, propertyType,
                    defaultValue, inherits, onChanged, coerce);
            }
            else
            {
                GenerateStyledPropertyField(sb, indent, dpPropertyName, propertyName, propertyType,
                    defaultValue, inherits, bindsTwoWayByDefault, onChanged, coerce);
            }

            sb.AppendLine($"{indent}    #endregion");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// The method the property's changes are reported to: the one named by
        /// <c>OnChanged</c>, or <c>On{Property}Changed</c> by convention.
        /// </summary>
        private IMethodSymbol? FindChangedCallback(string propertyName)
        {
            var name = GetAttributeValue<string>("OnChanged") ?? $"On{propertyName}Changed";

            return m_containingType.GetMembers(name)
                .OfType<IMethodSymbol>()
                .FirstOrDefault(IsPropertyChangedCallback);
        }

        private string? FindCoerceMethod(string conventionName)
        {
            var method = m_containingType.GetMembers(conventionName)
                .OfType<IMethodSymbol>()
                .FirstOrDefault(m => IsCoerceCallback(m));

            return method?.Name;
        }

        private bool IsPropertyChangedCallback(IMethodSymbol method)
        {
            // Avalonia callback signature: void OnPropertyChanged(AvaloniaPropertyChangedEventArgs<T> e)
            // or static void OnPropertyChanged(AvaloniaObject sender, AvaloniaPropertyChangedEventArgs e)
            if (method.ReturnsVoid)
            {
                if (method.Parameters.Length == 1)
                {
                    var paramType = method.Parameters[0].Type.ToDisplayString();
                    return paramType.Contains(ARGS_TYPE);
                }
                if (method.Parameters.Length == 2)
                {
                    var firstParam = method.Parameters[0].Type.ToDisplayString();
                    var secondParam = method.Parameters[1].Type.ToDisplayString();
                    return firstParam.Contains(OWNER_TYPE) &&
                           secondParam.Contains(ARGS_TYPE);
                }
            }

            return false;
        }

        private bool IsCoerceCallback(IMethodSymbol method)
        {
            // Avalonia coerce signature: T CoerceValue(AvaloniaObject sender, T value)
            if (!method.ReturnsVoid && method.Parameters.Length == 2)
            {
                var firstParam = method.Parameters[0].Type.ToDisplayString();
                return firstParam.Contains(OWNER_TYPE);
            }

            return false;
        }

        private void GenerateStyledPropertyField(
            StringBuilder sb,
            string indent,
            string dpPropertyName,
            string propertyName,
            string propertyType,
            object? defaultValue,
            bool inherits,
            bool bindsTwoWayByDefault,
            IMethodSymbol? onChanged,
            string? coerce)
        {
            var defaultBindingMode = bindsTwoWayByDefault ? "global::Avalonia.Data.BindingMode.TwoWay" : "default";
            var fieldType = $"global::Avalonia.StyledProperty<{propertyType}>";

            var registration = new StringBuilder();
            registration.Append($"global::Avalonia.AvaloniaProperty.Register<{m_containingType.Name}, {propertyType}>(");
            registration.Append($"nameof({propertyName})");

            if (defaultValue != null)
            {
                registration.Append($", defaultValue: {FormatDefaultValue(defaultValue, propertyType)}");
            }

            if (inherits)
            {
                registration.Append(", inherits: true");
            }

            if (bindsTwoWayByDefault)
            {
                registration.Append($", defaultBindingMode: {defaultBindingMode}");
            }

            if (!string.IsNullOrEmpty(coerce))
            {
                registration.Append($", coerce: {coerce}");
            }

            registration.Append(")");

            AppendPropertyField(sb, indent, dpPropertyName, fieldType, registration.ToString(),
                onChanged, m_containingType.Name, propertyType);
        }

        private void GenerateDirectProperty(
            StringBuilder sb,
            string indent,
            string dpPropertyName,
            string propertyName,
            string propertyType,
            object? defaultValue,
            bool bindsTwoWayByDefault,
            IMethodSymbol? onChanged)
        {
            var backingFieldName = $"m_{char.ToLowerInvariant(propertyName[0])}{propertyName.Substring(1)}";
            var defaultBindingMode = bindsTwoWayByDefault ? "global::Avalonia.Data.BindingMode.TwoWay" : "default";
            var fieldType = $"global::Avalonia.DirectProperty<{m_containingType.Name}, {propertyType}>";

            // Generate backing field
            sb.AppendLine($"{indent}    private {propertyType} {backingFieldName} = {FormatDefaultValue(defaultValue, propertyType)};");
            sb.AppendLine();

            var registration = new StringBuilder();
            registration.Append($"global::Avalonia.AvaloniaProperty.RegisterDirect<{m_containingType.Name}, {propertyType}>(");
            registration.Append($"nameof({propertyName}), ");
            registration.Append($"o => o.{backingFieldName}, ");

            // SetAndRaise, not a plain assignment. Avalonia raises nothing of its own for a
            // direct property — the notification is the setter's job — so a generated setter
            // that only wrote the field left the property silent: no callbacks, no bindings
            // out of it, and no sign that anything was wrong.
            registration.Append($"(o, v) => o.SetAndRaise({dpPropertyName}, ref o.{backingFieldName}, v)");

            if (defaultValue != null)
            {
                registration.Append($", unsetValue: {FormatDefaultValue(defaultValue, propertyType)}");
            }

            if (bindsTwoWayByDefault)
            {
                registration.Append($", defaultBindingMode: {defaultBindingMode}");
            }

            registration.Append(")");

            AppendPropertyField(sb, indent, dpPropertyName, fieldType, registration.ToString(),
                onChanged, m_containingType.Name, propertyType);
        }

        private void GenerateAttachedProperty(
            StringBuilder sb,
            string indent,
            string dpPropertyName,
            string propertyName,
            string propertyType,
            object? defaultValue,
            bool inherits,
            IMethodSymbol? onChanged,
            string? coerce)
        {
            var fieldType = $"global::Avalonia.AttachedProperty<{propertyType}>";

            // For attached properties, we use the non-generic RegisterAttached overload
            // that doesn't require TOwner type argument (which can't be static)
            var registration = new StringBuilder();
            registration.Append($"global::Avalonia.AvaloniaProperty.RegisterAttached<{AVALONIA_OBJECT}, {propertyType}>(");
            registration.Append($"\"{propertyName}\", typeof({m_containingType.Name})");

            if (defaultValue != null)
            {
                registration.Append($", defaultValue: {FormatDefaultValue(defaultValue, propertyType)}");
            }

            if (inherits)
            {
                registration.Append(", inherits: true");
            }

            if (!string.IsNullOrEmpty(coerce))
            {
                registration.Append($", coerce: {coerce}");
            }

            registration.Append(")");

            // An attached property belongs to no instance, so its callback has to be static.
            // An instance one would be handed an AvaloniaObject it has no relationship with.
            var callback = onChanged is { IsStatic: true } ? onChanged : null;

            AppendPropertyField(sb, indent, dpPropertyName, fieldType, registration.ToString(),
                callback, AVALONIA_OBJECT, propertyType);

            if (onChanged != null && callback == null)
            {
                sb.AppendLine($"{indent}    // '{onChanged.Name}' is not subscribed: an attached property's callback must be static,");
                sb.AppendLine($"{indent}    // because the object it fires for is not an instance of {m_containingType.Name}.");
                sb.AppendLine();
            }

            // Generate Get method
            sb.AppendLine($"{indent}    public static {propertyType} Get{propertyName}({AVALONIA_OBJECT} obj)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return obj.GetValue({dpPropertyName});");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // Generate Set method
            sb.AppendLine($"{indent}    public static void Set{propertyName}({AVALONIA_OBJECT} obj, {propertyType} value)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        obj.SetValue({dpPropertyName}, value);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        /// <summary>
        /// Emits the property field. Without a callback that is a plain initializer; with one
        /// the initializer calls a factory that registers the property and subscribes to its
        /// changes in the same breath.
        /// </summary>
        /// <remarks>
        /// A factory rather than a static constructor, and deliberately. Avalonia has no
        /// changed-callback parameter on Register — notification arrives through the
        /// property's Changed observable — so somebody has to subscribe, and a generated
        /// static constructor would collide with the hand-written one that authors of these
        /// controls have had to write until now. A field initializer composes with theirs.
        /// </remarks>
        private void AppendPropertyField(
            StringBuilder sb,
            string indent,
            string dpPropertyName,
            string fieldType,
            string registration,
            IMethodSymbol? onChanged,
            string ownerType,
            string propertyType)
        {
            if (onChanged == null)
            {
                sb.AppendLine($"{indent}    public static readonly {fieldType} {dpPropertyName} =");
                sb.AppendLine($"{indent}        {registration};");
                sb.AppendLine();

                return;
            }

            var factoryName = $"Register{dpPropertyName}";

            sb.AppendLine($"{indent}    public static readonly {fieldType} {dpPropertyName} = {factoryName}();");
            sb.AppendLine();

            sb.AppendLine($"{indent}    private static {fieldType} {factoryName}()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var property =");
            sb.AppendLine($"{indent}            {registration};");
            sb.AppendLine();
            // Called in its static form: an extension method would need a using directive, and
            // generated code cannot assume what the file it lands next to has imported.
            sb.AppendLine($"{indent}        global::Avalonia.AvaloniaObjectExtensions.AddClassHandler<{ownerType}, {propertyType}>(");
            sb.AppendLine($"{indent}            property.Changed, (owner, args) => {Invocation(onChanged)});");
            sb.AppendLine();
            sb.AppendLine($"{indent}        return property;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        /// <summary>
        /// How the callback is called from the subscription, given its shape: an instance
        /// method is called on the object that changed, a static one is handed it.
        /// </summary>
        private static string Invocation(IMethodSymbol callback)
        {
            var arguments = callback.Parameters.Length == 2 ? "owner, args" : "args";

            return callback.IsStatic
                ? $"{callback.Name}({arguments})"
                : $"owner.{callback.Name}({arguments})";
        }

        private string FormatDefaultValue(object? value, string propertyType)
        {
            if (value == null)
                return $"default({propertyType})!";

            if (value is string str)
                return $"\"{str}\"";
            if (value is bool b)
                return b ? "true" : "false";
            if (value is char c)
                return $"'{c}'";
            if (value is float f)
                return $"{f}f";
            if (value is double d)
                return $"{d}d";
            if (value is decimal m)
                return $"{m}m";
            if (value is long l)
                return $"{l}L";
            if (value is ulong ul)
                return $"{ul}UL";
            if (value is uint ui)
                return $"{ui}U";

            return value.ToString() ?? $"default({propertyType})!";
        }

        private T? GetAttributeValue<T>(string propertyName)
        {
            var namedArg = m_attributeData.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == propertyName);

            if (namedArg.Value.Value is T typedValue)
                return typedValue;

            return default;
        }

        #endregion
    }
}
